production:
  create_collections_tuesday:
    class: CreateCollectionsJob
    args: ["Tuesday"]
    schedule: "0 15 * * 2"  # Runs every Tuesday at 3 PM UTC

  create_collections_wednesday:
    class: CreateCollectionsJob
    args: ["Wednesday"]
    schedule: "0 15 * * 3"  # Runs every Wednesday at 3 PM UTC

  create_collections_thursday:
    class: CreateCollectionsJob
    args: ["Thursday"]
    schedule: "0 15 * * 4"  # Runs every Thursday at 3 PM UTC
